### ISSUE TITLE
初始化语句需要更新

### ISSUE THREAD

**Issue by feacx** [continew-org/continew-admin#28]
### Bug 描述

首先感谢作者`Charles`提供与维护本项目，这个项目使用的技术栈我相信都是精挑细选，与我不谋而合。感谢您。

我通过文档中的指导一步步运行起来后，控制台输出了 `sys_log` 表的 `description` 和 `module` 字段不允许为空且未设置默认值，我手动将数据库里的这两个字段改为允许为空、默认值为NULL后，一切恢复了正常。我知道这个不是正确的解决方法，应该需要去看代码的逻辑，为何会产生为空的数据。但是我遇到了先反馈。

我认为这个问题的发生是在作者的电脑发生时，作者手动修改了数据库，但未更新初始化SQL语句文件，然而也没用其他人提出这个问题，所以这个SQL文件将永远不会更新，希望作者更新一下此文件，后续其他人不会遇到相同问题，也不会遗失重要的日志。

### 复现步骤

从0创建项目。
一定要用一个崭新的数据库！！
项目启动后，访问Swagger，并随意点击几个API。
查看控制台

### 预期结果

不报错

### 环境信息

release - 2.2.0

### 确认

- [X] 阅读[文档](https://doc.charles7c.top/admin/other/faq.html)
- [X] 根据报错信息百度或 Google 一下
- [X] 搜索是否有其他人提交过类似的 issue，如果对应 issue 尚未解决，您可以先订阅关注该 issue（为了方便后来者查找问题解决方法，请尽量避免创建重复的 issue）

**Comment by Charles7c** [comment]
感谢您的使用，v2.2.0 版本的系统日志功能是重新基于 `ContiNew Starter` 的 [continew-starter-log-httptrace-pro](https://github.com/Charles7c/continew-starter/tree/1.1.x/continew-starter-log/continew-starter-log-httptrace-pro) 组件（ v1.1.0 版本）开发的，这一日志组件设计的时候，可以根据个人需要调整记录的内容，默认情况下不记录 `description` 和 `module` 信息，以记录 HTTP 请求信息为主。

但是，我在适配的时候，已经在 ContiNew Admin `application.yml` 中增加了这段配置，要求它记录 `description` 和 `module` 信息，以适配本系统的操作日志功能。
```yaml
--- ### 日志配置
continew-starter.log:
  enabled: true
  # 包含信息
  include:
    - DESCRIPTION
    - MODULE
    - REQUEST_HEADERS
    - REQUEST_BODY
    - IP_ADDRESS
    - BROWSER
    - OS
    - RESPONSE_HEADERS
    - RESPONSE_BODY
```

方便的话，发一下你点击报错的 API Controller 定义情况以及对应日志配置，也可以加一下交流群沟通一下。
